"""create tasks table

Revision ID: 4c6636b7fc2b
Revises: 
Create Date: 2026-06-19 20:44:11.599828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c6636b7fc2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=255),
               nullable=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.alter_column('tasks', 'status',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
